project:
  type: book
  output-dir: _output

book:
  title: "VMRDH-Jobs"
  author: 
    name: Srirama Bhamidipati
    email: sk.bhamidipati@rotterdam.nl
    affiliations:
      - name: Gemeente Rotterdam
        address: Wilhelminakade 179 · 3072 AP 
        city: Rotterdam
        
  date: "now"
  # date-format: YYYY-MM-DDTHH:mm:ssZ
  navbar:
    background: primary
    search: true
  page-navigation: true
  downloads: [pdf]
  chapters:
    - index.qmd
    - part: Standard_uitvoer/intro.qmd
      chapters:
       # - Standard_uitvoer/01_MatrixBewerkingen/intro.qmd
        - Standard_uitvoer/02_MatrixCompressies/intro.qmd
        - Standard_uitvoer/03_Voertuigprestaties/intro.qmd
       # - Standard_uitvoer/04_Thermopunten/intro.qmd
        - Standard_uitvoer/05_(Skim)Matrix_Exports/intro.qmd
        - Standard_uitvoer/06_Bereikbaarheid/intro.qmd
        - Standard_uitvoer/07_SelectedLinkCompress/intro.qmd
        - Standard_uitvoer/08_INEXDO/intro.qmd
        - Standard_uitvoer/11_Milieu(Goudappel)/intro.qmd
        
    
 

bibliography: references.bib

format:
  html:
    theme: cosmo
    fontsize: 1.27rem
    css: style.css
    toc: true
    toc-title: Job index
    code-overflow: scroll
    code-line-numbers: true
    
  pdf:
    documentclass: scrreprt
    keep-tex: true
    toccolor: blue
    toc-title: Job index
    include-in-header: header.tex
    variables:
      commit_hash: !expr Sys.getenv("COMMIT_HASH")
      
    
execute:
  echo: true
  commit-id: 

editor: visual

margin-footer: |
  doc-id-{{< env git_hash >}}
  
body-footer: | 
  doc-id: {{< env git_hash >}}
