on:
  push:
    branches:
      - user

name: Render and Publish

# you need these permissions to publish to GitHub pages
permissions: 
    contents: write
    pages: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # To install LaTeX to build PDF book 
          tinytex: true 
          # uncomment below and fill to pin a version
          # version: SPECIFIC-QUARTO-VERSION-HERE
      
      # add software dependencies here and any libraries
      
   

      # From https://github.com/r-lib/actions/tree/v2-branch/setup-r
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages:
            any::knitr
            any::rmarkdown
            any::downlit
            any::xml2

   

  

      # NOTE: If Publishing to GitHub Pages, set the permissions correctly (see top of this yaml)
      - name: Publish to GitHub Pages (and render) 
        uses: quarto-dev/quarto-actions/render@v2
        with:
         path: docs
         to: pdf
      - name: main
        run: |
          cd /home/runner/work/docs/
          tree
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: my_pdf
          path: /home/runner/work/delete/delete/test/docs/test.pdf
      - name: Generate release tag
        id: generate_release_tag
        uses: amitsingh-007/next-release-tag@v5.0.0
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           tag_prefix: 'OTjobs_guide-v'
           tag_template: 'yyyy.mm.dd.i'

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          tag: ${{ steps.generate_release_tag.outputs.next_release_tag }}
          generateReleaseNotes: true
          makeLatest: true
          artifacts: "/home/runner/work/delete/delete/test/docs/test.pdf"
          token: ${{ secrets.GITHUB_TOKEN }}
           
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
